[user]
name = "Aleksey Kuznetsov"
email = "zummenix@gmail.com"

[ui]
default-command = ["log", "--limit", "13"]
diff.format = "git"
pager = ["sh", "-c", "delta --diff-so-fancy | less -RFX"]

[templates]
log = 'log_oneline'
log_node = '''
if(self,
  if(current_working_copy, "@",
    if(root, "┴",
      if(immutable, label("timestamp", "✦"), "⦿")
    )
  ),
  label("elided", "◌"),
)
'''

[template-aliases]
prompt_show_oneline = '''
concat(
  "[" ++ builtin_change_id_with_hidden_and_divergent_info ++ "] ",
  if(empty, "○", "⦿") ++ " ",
  if(description, description.first_line(), description_placeholder),
  "\n",
)
'''

log_oneline = '''
if(root,
  builtin_log_root(change_id, commit_id),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        committer.timestamp().local().format("%F %R"),
        if(author.email(), author.username().substr(0, 10), email_placeholder),
        builtin_change_id_with_hidden_and_divergent_info,
        if(conflict, label("conflict", "conflict")),
        if(empty, label("empty", "(empty)")),
        if(description, description.first_line(), description_placeholder),
        branches,
        tags,
        working_copies,
        git_head,
      ) ++ "\n",
    ),
  )
)
'''

