"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Aleksey Kuznetsov"
email = "zummenix@gmail.com"

[ui]
default-command = ["log", "--limit", "13"]
diff-formatter = ":git"
pager = ["sh", "-c", "delta --diff-so-fancy | less -RX"]
bookmark-list-sort-keys = ["committer-date-"]

[templates]
log = 'log_oneline'
log_node = '''
if(self,
  if(current_working_copy, "@",
    if(root, "┴",
      if(immutable, label("timestamp", "✦"), "⦿")
    )
  ),
  label("elided", "◌"),
)
'''
git_push_bookmark = '"zummenix/push-" ++ change_id.short()'

[template-aliases]
prompt_show_oneline = '''
concat(
  "[" ++ format_short_change_id_with_hidden_and_divergent_info(self) ++ "] ",
  if(empty, "○", "⦿") ++ " ",
  if(description, description.first_line(), description_placeholder),
  "\n",
)
'''

log_oneline = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        committer.timestamp().local().format("%F %R"),
        if(author.email(), author.email().local().substr(0, 10), email_placeholder),
        format_short_change_id_with_hidden_and_divergent_info(self),
        if(conflict, label("conflict", "conflict")),
        if(empty, label("empty", "(empty)")),
        if(description, description.first_line(), description_placeholder),
        bookmarks,
        tags,
        working_copies,
        if(self.git_head(), label("git_head", "HEAD")),
      ) ++ "\n",
    ),
  )
)
'''

