[user]
name = "Aleksey Kuznetsov"
email = "zummenix@gmail.com"

[ui]
default-command = "status"
diff.format = "git"
pager = ["sh", "-c", "delta --diff-so-fancy | less -RFX"]

[templates]
log = 'builtin_log_comfortable'

[template-aliases]
prompt_show_oneline = '''
concat(
  "[" ++ builtin_change_id_with_hidden_and_divergent_info ++ "] ",
  if(empty, "○", "⦿") ++ " ",
  if(description, description.first_line(), description_placeholder),
  "\n",
)
'''
