theme = "base16-ocean"

[editor]
line-number = "relative"
cursorline = true
rulers = [100]
color-modes = true

[editor.cursor-shape]
insert = "underline"
normal = "block"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["spacer"]
right = ["workspace-diagnostics", "selections", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false
