theme = "base16-ocean"

[editor]
line-number = "relative"
cursorline = true
rulers = [100]
color-modes = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
prefix-len = 7

[editor.cursor-shape]
insert = "underline"
normal = "block"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["spacer"]
right = ["workspace-diagnostics", "selections", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[keys.normal."space"]
# This does't work quite as expected.
# See https://github.com/helix-editor/helix/discussions/13023
# Possibly waiting on https://github.com/helix-editor/helix/issues/8853
i = [
  ":toggle-option inline-diagnostics.other-lines hint disable",
  ":toggle-option inline-diagnostics.cursor-line hint disable"
]

