#!/usr/bin/env bash

# The script transfers provided *.png or *.mp4 files using SFTP.
#
# Dependencies (all available on macOS without additional installation):
# - open - open a link in a browser
# - scp - copy a media file securely to a server (SFTP)
#
# Usage:
# mshare file

set -e

# SFTP sharing configuration.
SFTP_PORT=2221
SFTP_USER=AlekseyKuznetsov
SFTP_HOST=jing.saritasa.com
DIR="$HOME/Desktop"

for file in "$@"; do
    # File name format configuration.
    if echo "$file" | grep -IE ".*.(png|jpg)" > /dev/null; then
        EXT=$(basename "$file")
        EXT="${EXT##*.}"
        FILE_NAME=$(date "+Screenshot-%Y-%m-%d-%H-%M-%S.$EXT")
    elif echo "$file" | grep -Ie ".*.mp4" > /dev/null; then
        FILE_NAME=$(date "+Screenrecording-%Y-%m-%d-%H-%M-%S.mp4")
    else
        continue
    fi

    FILE_PATH="$DIR/$FILE_NAME"

    cp "$file" "$FILE_PATH"
    echo "Uploading..."
    scp -P $SFTP_PORT "$FILE_PATH" "$SFTP_USER@$SFTP_HOST:/"
    open "https://$SFTP_HOST/$SFTP_USER/$FILE_NAME"
done

