#!/usr/bin/env bash

# Enables localhost socks proxy for the network and starts ssh tunneling.

IDENTITY_FILE="$1"
USER="$2"
INSTANCE_ID="$3"
PORT="1313"

if test -z "$IDENTITY_FILE" -o -z "$USER" -o -z "$INSTANCE_ID"; then
    echo "Usage: socks <identity-file> <user> <instance-id>"
    exit 1
fi

PUBLIC_DNS_NAME=$(aws --profile my ec2 describe-instances --instance-ids "$INSTANCE_ID" --query 'Reservations[].Instances[].PublicDnsName' --output text)
if test -z "$PUBLIC_DNS_NAME"; then
    echo "The instance is probably not running!"
    exit 1
fi
DESTINATION="$USER@$PUBLIC_DNS_NAME"

enable_proxy() {
    networksetup -setsocksfirewallproxy Wi-Fi localhost "$PORT"
    networksetup -setsocksfirewallproxystate Wi-Fi on
    echo "SOCKS proxy enabled."
}

disable_proxy() {
    echo "" # Just for beauty when ^C :)
    networksetup -setsocksfirewallproxystate Wi-Fi off
    echo "SOCKS proxy disabled."
}

trap disable_proxy INT

enable_proxy

echo "Tunneling..."
ssh -i "$IDENTITY_FILE" -D "$PORT" -gCN "$DESTINATION"
