#!/usr/bin/env bash

# Echos out a description of a task.
function desc {
    tput bold && tput setaf 2
    echo ""
    echo "§ $1"
    tput sgr0
}

# Echos out an error.
function error {
    tput bold && tput setaf 1
    echo "  $1"
    tput sgr0
}

# Ensures a directory exists.
function dir {
    if test -d "$1"; then
        echo "$1 exists."
    else
        mkdir "$1" && echo "$1 has been created."
    fi
}

# Ensures a git repo is up to date.
function pull {
    if test -d "$2"; then
        cd "$2" || exit 1
        { jj git fetch && (jj new master || jj new main); } || git pull
    else
        git clone "$1" "$2"
    fi
}

function npm-install {
    desc "NPM install $1"
    npm install --global "$1"
}

# Installs a tool.
function cargo-install {
    desc "Installing $1"
    cargo install "$1"
}

# Creates a symbolic link to a file or a directory.
function symlink {
    ln -hfs "$1" "$2"
    ls -l "$2"
}

CONFIG_DIR="$HOME/.config"
PROJECTS_DIR="$HOME/projects"

desc "Ensure xcode command line tools are installed"
xcode-select --install

desc "Ensure homebrew is up to date"
if test -x "$(command -v brew)"; then
    brew update
else
    error "brew is not installed. Please install brew manually"
    exit 1
fi

desc "Ensure rustup is installed"
if test -x "$(command -v rustup)"; then
    echo "rustup is installed."
else
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

desc "Ensure rust is installed and up to date"
rustup self update
rustup update stable

rustup component add rust-analyzer
rustup component add llvm-tools-preview

desc "Ensure ~/.config directory exists"
dir "$CONFIG_DIR"

desc "Ensure ~/projects directory exists"
dir "$PROJECTS_DIR"

desc "Remove legacy symlinks"
unlink "$CONFIG_DIR/zellij" || true
unlink "$CONFIG_DIR/alacritty" || true
unlink "$CONFIG_DIR/nvim" || true

desc "Install/cleanup dependencies using Brewfile"
brew bundle --cleanup --file "$PROJECTS_DIR/dotfiles/Brewfile" -v

desc "Symlink helix settings"
symlink "$PROJECTS_DIR/dotfiles/helix" "$CONFIG_DIR/helix"

desc "Symlink fish settings"
symlink "$PROJECTS_DIR/dotfiles/fish" "$CONFIG_DIR/fish"

desc "Symlink wezterm settings"
symlink "$PROJECTS_DIR/dotfiles/wezterm" "$CONFIG_DIR/wezterm"

desc "Symlink tig settings"
symlink "$PROJECTS_DIR/dotfiles/tig/.tigrc" "$HOME/.tigrc"

desc "Symlink git config"
symlink "$PROJECTS_DIR/dotfiles/git/.gitconfig" "$HOME/.gitconfig"

desc "Symlink global git ignore"
symlink "$PROJECTS_DIR/dotfiles/git/.gitignore-global" "$HOME/.gitignore-global"

desc "Symlink jj config"
symlink "$PROJECTS_DIR/dotfiles/jj/config.toml" "$HOME/Library/Application Support/jj/config.toml"

npm-install "vscode-langservers-extracted"

desc "Installing xcopen"
pull "git@github.com:zummenix/xcopen.git" "$PROJECTS_DIR/xcopen"
cargo install --path "$PROJECTS_DIR/xcopen" && \
    sh "$PROJECTS_DIR"/dotfiles/scripts/strip-pretty xcopen

desc "Installing mprovision"
pull "git@github.com:zummenix/mprovision.git" "$PROJECTS_DIR/mprovision"
cargo install --path "$PROJECTS_DIR/mprovision/crates/cli" && \
    sh "$PROJECTS_DIR"/dotfiles/scripts/strip-pretty mprovision

cargo-install cargo-bloat
cargo-install cargo-outdated
cargo-install cargo-insta
cargo-install cargo-diet
cargo-install cargo-audit
cargo-install cargo-nextest
cargo-install cargo-llvm-cov
cargo-install cargo-semver-checks
cargo-install cargo-leptos
cargo-install leptosfmt

cargo-install bottom
cargo-install ripgrep
cargo-install tokei
cargo-install typos-cli
cargo-install git-delta
cargo-install ast-grep

cargo-install itm
cargo-install cargo-binutils

desc "Switch current shell to fish"
if test "$(echo "$SHELL" | grep fish)"; then
    echo "Already fish."
else
    LINE="$(which fish)"
    FILE=/etc/shells
    grep -qF -- "$LINE" "$FILE" || echo "$LINE" | sudo tee -a "$FILE"
    chsh -s "$LINE" && echo "Done. Please open a new terminal tab or window to see the change."
fi
