#!/usr/bin/env bash

set -e

function clean_dir {
    if test -d "$1"; then
        du -hd0 "$1"
        trash "$1"
    else
        echo "        $1"
    fi
}

clean_dir "$HOME/Library/Developer/CoreSimulator"
clean_dir "$HOME/Library/Developer/Xcode/Archives"
clean_dir "$HOME/Library/Developer/Xcode/Products"
clean_dir "$HOME/Library/Developer/Xcode/iOS Device Logs"
clean_dir "$HOME/Library/Developer/Xcode/UserData/IB Support"
clean_dir "$HOME/Library/Developer/Xcode/DerivedData"
clean_dir "$HOME/Library/Developer/Xcode/iOS DeviceSupport"
clean_dir "$HOME/Library/Caches/com.apple.dt.Xcode"
clean_dir "$HOME/Library/Caches/Google"
clean_dir "$HOME/Library/Caches/Homebrew"
clean_dir "$HOME/Library/Caches/CocoaPods"
clean_dir "$HOME/Library/Caches/org.carthage.CarthageKit"
clean_dir "$HOME/.cargo/registry"
clean_dir "$HOME/.cargo/git"

# Important for proper work of Interface Builder after deleting its directory.
launchctl list | grep CoreSimulatorService | cut -f3 | xargs launchctl remove

# Opening xcode will recreate all simulators. After that we need to remove unnecessary simulators.
echo "Opening Xcode, waiting for it to be closed..."
open -W -a Xcode

xcrun simctl delete all
xcrun simctl create "iPhone 13 Pro" com.apple.CoreSimulator.SimDeviceType.iPhone-13-Pro
xcrun simctl create "iPad Air 4th gen" com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-

trash -e
