#!/usr/bin/env bash

# Updates rustup and rustc, installs some tools

set -ex

brew upgrade

rustup self update
rustup update stable

cargo install cargo-bloat
cargo install cargo-outdated
cargo install cargo-insta
cargo install cargo-diet

cargo install ytop
