#!/usr/bin/env bash

# Iterates over arguments and converts mov to mp4 using ffmpeg.

for file in "$@"; do
    if echo "$file" | grep -Ie ".*.mov" > /dev/null; then
        OUTPUT="${file%.*}.mp4"
        ffmpeg -i "$file" -qscale 0 "$OUTPUT" && echo "$OUTPUT"
    fi
done
