#!/usr/bin/env bash

# A script that helps me manage my own patches to helix editor.
# It will rebase each patch to the master to check compatibility,
# then create a `sandbox` branch and try to rebase each patch.
# And finally, it will run `cargo install`.
#
# Should be run inside helix git repository.

# Echos out a description of a task.
function desc {
    tput bold && tput setaf 2
    echo ""
    echo "§ $1"
    tput sgr0
}

my_patch_branches=(
  indication-of-current-search-match
  modern-rust
)

desc "Pulling upstream master"
git checkout master
git pull upstream master
if test $? -ne 0; then
  exit 1
fi

for patch_branch in "${my_patch_branches[@]}"; do
  desc "Pulling $patch_branch"
  git checkout "$patch_branch"
  if test $? -ne 0; then
    git checkout master
    exit 1
  fi

  git pull --rebase
  if test $? -ne 0; then
    git checkout master
    exit 1
  fi

  desc "Updating $patch_branch"
  git rebase master
  if test $? -ne 0; then
    git rebase --abort
    git checkout master
    exit 1
  fi

  desc "Pushing back $patch_branch"
  git push --force
  if test $? -ne 0; then
    git checkout master
    exit 1
  fi
done

desc "Preparing sandbox"
git branch -D sandbox || true
git checkout -b sandbox

for patch_branch in "${my_patch_branches[@]}"; do
  desc "Applying $patch_branch"
  git rebase "$patch_branch"
  if test $? -ne 0; then
    git rebase --abort
    git checkout master
    exit 1
  fi
done

desc "Pushing sandbox"
git push --force --set-upstream origin sandbox

desc "Compiling helix"
cargo install --path helix-term --locked && strip-pretty hx

desc "Syncing my master"
git checkout master
git push
