#!/usr/bin/env bash

set -e

FILE_NAME=$(date "+Screenshot-%Y-%m-%d-%H-%M-%S.png")
DIR="$HOME/Desktop/Screenshots"

if ! test -d "$DIR"; then
    mkdir "$DIR"
fi

FILE_PATH="$DIR/$FILE_NAME"

echo "Space key - mouse selection/window selection."
echo "Screenshot will be open in the Preview.app. Quit (Cmd+Q) the Preview.app to continue."
screencapture -i "$FILE_PATH"
if ! test -s "$FILE_PATH"; then
    exit 0
fi

open -n -W -a "Preview" "$FILE_PATH"

read -p "Copy to clipboard or Upload using SFTP (c/u)?: " DESTINATION

if test "$DESTINATION" = "c"; then
    osascript -e "set the clipboard to (read (POSIX file \"$FILE_PATH\") as JPEG picture)"
    echo "Copied to clipboard"
elif test "$DESTINATION" = "u"; then
    echo "Uploading..."
    scp -P 2221 "$FILE_PATH" AlekseyKuznetsov@jing.saritasa.com:/
    open "https://jing.saritasa.com/AlekseyKuznetsov/$FILE_NAME"
fi

