#!/usr/bin/env bash

# Enables localhost socks proxy for the network and starts ssh tunneling.

IDENTITY_FILE="$1"
DESTINATION="$2"
PORT="1313"

if test -z "$IDENTITY_FILE" -o -z "$DESTINATION"; then
    echo "Usage: socks .ssh/my-key.pem user@host"
    exit 1
fi

enable_proxy() {
    networksetup -setsocksfirewallproxy Wi-Fi localhost "$PORT"
    networksetup -setsocksfirewallproxystate Wi-Fi on
    networksetup -setproxybypassdomains Wi-Fi youtube.com
    echo "SOCKS proxy enabled."
}

disable_proxy() {
    echo "" # Just for beauty when ^C :)
    networksetup -setsocksfirewallproxystate Wi-Fi off
    echo "SOCKS proxy disabled."
}

trap disable_proxy INT

enable_proxy

echo "Tunneling..."
ssh -i "$IDENTITY_FILE" -D "$PORT" -CN "$DESTINATION"
