#!/usr/bin/env bash

# Command line helper to run AnyConnect VPN client from the terminal.

BIN_DIR=/opt/cisco/secureclient/bin

_print_usage() {
    echo "Usage:"
    echo "  vpn-connect start <host>"
    echo "  vpn-connect stop"
}

_stop() {
    echo "" # Just for beauty when ^C :)

    sudo -vp "Please type a password for %u to stop the vpn: "
    $BIN_DIR/vpn disconnect

    sudo -k # Reset auth

    exit 0
}

COMMAND="$1"

if test "$COMMAND" = "start"; then
    VPNHOST="$2"
    if test -z "$VPNHOST"; then
        _print_usage
        exit 1
    fi

    trap _stop INT

    sudo -vp "Please type a password for %u to start the vpn: "

    $BIN_DIR/vpn connect "$VPNHOST"

    echo "Press [Ctrl+C] to stop the VPN..."

    while true
    do
        if $BIN_DIR/vpn state | grep ">> state: Disconnected" 1>> /dev/null; then
            echo "$(date +"%H:%M:%S") Disconnected"
        fi

        sleep 60
    done
elif test "$COMMAND" = "stop"; then
    _stop
else
    _print_usage
    exit 1
fi
