#!/usr/bin/env bash

# Simplifies process of switching between Xcode versions.

echo "Closing all Simulator instances"
osascript -e 'tell app "Simulator" to quit'

echo "Closing all Xcode instances"
osascript -e 'tell app "Xcode" to quit'

CURRENT_XCODE=$(xcode-select -p)

find /Applications -type d -maxdepth 1 -name 'Xcode*' -print |
    fzf --header "Current is $CURRENT_XCODE" |
    xargs -I{} sudo xcode-select --switch "{}/Contents/Developer" &&
    xcode-select --print-path
